### ISSUE TITLE
ClassNotFoundException? File missing

### ISSUE THREAD

**Issue by TheKillerTacos** [FastTweak/SimpleSkyWars#2]
[Server thread/CRITICAL]: ClassNotFoundException: "Class SkygridRex\skywars\map\SkyBlockGenerator not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 128

SkyBlockGenerator?? forgot to modify, Import something @SkygridRex ?

**Comment by SkygridRex** [comment]
Give a few days

**Comment by TheKillerTacos** [comment]
ok, Locking for further Conversation

**Comment by SkygridRex** [comment]
Added

**Comment by TheKillerTacos** [comment]
Ok, Ill test the plugin again for any errors so i can fix them!

**Comment by SkygridRex** [comment]
@TheKillerTacos please update block list in PEBlock.php

**Comment by TheKillerTacos** [comment]
Ok, and why didnt you asked me this on gitter? btw sure

**Comment by SkygridRex** [comment]
Please do it!

**Comment by TheKillerTacos** [comment]
[Server thread/NOTICE]: RuntimeException: "Non-static method SkygridRex\skywars\Arena::loadArenas() should not be called statically, assuming $this from incompatible context" (E_DEPRECATED) in "myzip:///plugins/SimpleSkyWars-master.zip#src/SkygridRex/skywars/SkyWarsConfiguration" at line 59

**Comment by SkygridRex** [comment]
Some config files in resources are missing too
